# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 70, 589, 349))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600; color:#00aaff;\">Bit Pattern Frequency based attack</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://link.springer.com/chapter/10.1007/978-3-319-57454-7_49\"><span style=\" text-decoration: underline; color:#0000ff;\">Paper URL</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; text-decoration: underline; color:#0000ff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue Regular\',\'sans-serif\'; font-size:18px; font-weight:696; color:#00aaff; background-color:#ffffff;\">Abstract:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'TkfqsvRtmjjlCMR9\'; font-size:8.9664pt; color:#000000;\">Privacy-preserving record linkage (PPRL) is the process of </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'TkfqsvRtmjjlCMR9\'; font-size:8.9664pt; color:#000000;\">identifying records that represent the same entity across databases held </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'TkfqsvRtmjjlCMR9\'; font-size:8.9664pt; color:#000000;\">by difffferent organizations without revealing any sensitive information </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'TkfqsvRtmjjlCMR9\'; font-size:8.9664pt; color:#000000;\">about these entities. A popular technique used in PPRL is Bloom fifilter </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'TkfqsvRtmjjlCMR9\'; font-size:8.9664pt; color:#000000;\">encoding, which has shown to be an effiffifficient and effffective way to encode </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'TkfqsvRtmjjlCMR9\'; font-size:8.9664pt; color:#000000;\">sensitive information into bit vectors while still enabling approximate </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'TkfqsvRtmjjlCMR9\'; font-size:8.9664pt; color:#000000;\">matching of attribute values. However, the encoded values in Bloom fifil</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'TkfqsvRtmjjlCMR9\'; font-size:8.9664pt; color:#000000;\">ters are vulnerable to cryptanalysis attacks. Under specifific conditions, </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'TkfqsvRtmjjlCMR9\'; font-size:8.9664pt; color:#000000;\">these attacks are successful in that some frequent sensitive attribute val</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'TkfqsvRtmjjlCMR9\'; font-size:8.9664pt; color:#000000;\">ues can be re-identifified. In this paper we propose and evaluate on real </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'TkfqsvRtmjjlCMR9\'; font-size:8.9664pt; color:#000000;\">databases a novel effiffifficient attack on Bloom fifilters. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'TkfqsvRtmjjlCMR9\'; font-size:8.9664pt; color:#000000;\">Our approach is based on the construction principle of Bloom fifilters of hashing elements of sets into bit positions. The attack is independent of the encoding function and its parameters used, it can correctly re-identify sensitive attribute values even when various recently proposed hardening techniques have </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'TkfqsvRtmjjlCMR9\'; font-size:8.9664pt; color:#000000;\">been applied, and it runs in a few seconds instead of hours.</span> </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-weight:600; color:#00aaff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#00aaff;\">Attack Process Info:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'NimbusRomNo9L-Medi\'; font-size:9.46485pt; font-weight:600; color:#000000;\">Step 1: </span><span style=\" font-family:\'DdxfhcPgdkchCMBX10\'; font-size:9.9626pt; font-weight:600; color:#000000;\">Candidate Q-Gram Set Generation</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'NimbusRomNo9L-Medi\'; font-size:9.46485pt; font-weight:600; color:#000000;\">Step 2: </span><span style=\" font-family:\'DdxfhcPgdkchCMBX10\'; font-size:9.9626pt; font-weight:600; color:#000000;\">Attribute Value Re-identifification</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'NimbusRomNo9L-Medi\'; font-size:9.46485pt; font-weight:600; color:#000000;\">Step 3: </span><span style=\" font-family:\'DdxfhcPgdkchCMBX10\'; font-size:9.9626pt; font-weight:600; color:#000000;\">Analysis and Limitations</span> </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#00aaff;\">Parameters detail:</span><span style=\" font-weight:600;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:9.8pt; font-weight:600; color:#000000;\">min_freq: </span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:9.8pt; color:#000000;\">  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:9.8pt; color:#000000;\">is the minimum frequency of Bloom filters and<br />attribute values to consider in the analysis</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'JetBrains Mono\',\'monospace\'; font-size:9.8pt; color:#000000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:9.8pt; font-weight:600; color:#000000;\">num_freq_attr_val_list</span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:9.8pt; color:#808080;\">:  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:9.8pt; color:#000000;\">is a list with the numbers of most frequent<br />attribute values from the analysis file we aim to<br />re-identify</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
